/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.33).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package net.catenax.semantics.framework.aas.api.proxy;

import io.swagger.annotations.Api;
import net.catenax.semantics.framework.aas.model.OperationRequest;
import net.catenax.semantics.framework.aas.model.OperationResult;
import net.catenax.semantics.framework.aas.model.Submodel;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-03-04T18:11:14.812382100+01:00[Europe/Berlin]")
@Validated
@Api(tags="AAS", value = "aas", description = "Simple AAS Adapter API")
public interface AssetIdentifierApi {

    AssetIdentifierApiDelegate getDelegate();

    @Operation(summary = "Returns the Operation result of an asynchronous invoked Operation", description = "", tags={ "Submodel Interface" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Operation result object", content = @Content(mediaType = "application/json", schema = @Schema(implementation = OperationResult.class))) })
    @RequestMapping(value = "/{assetIdentifier}/aas/{submodelIdentifier}/submodel/submodel-elements/{idShortPath}/operation-results/{handleId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<OperationResult> getOperationAsyncResult(@PathVariable(name = "idsOffer",value="", required = false) String idsOffer, @Parameter(in = ParameterIn.PATH, description = "The Asset Administration Shells’s unique id (BASE64-URL-encoded)", required=true, schema=@Schema()) @PathVariable("assetIdentifier") String assetIdentifier, @Parameter(in = ParameterIn.PATH, description = "The Submodel’s unique id (BASE64-URL-encoded)", required=true, schema=@Schema()) @PathVariable("submodelIdentifier") String submodelIdentifier, @Parameter(in = ParameterIn.PATH, description = "IdShort path to the submodel element (dot-separated), in this case an operation", required=true, schema=@Schema()) @PathVariable("idShortPath") String idShortPath, @Parameter(in = ParameterIn.PATH, description = "The returned handle id of an operation’s asynchronous invocation used to request the current state of the operation’s execution (BASE64-URL-encoded)", required=true, schema=@Schema()) @PathVariable("handleId") String handleId, @Parameter(in = ParameterIn.QUERY, description = "" ,schema=@Schema(allowableValues={ "normal", "value" }
, defaultValue="normal")) @Valid @RequestParam(value = "content", required = false, defaultValue="normal") String content) {
        return getDelegate().getOperationAsyncResult(idsOffer,assetIdentifier, submodelIdentifier, idShortPath, handleId, content);
    }

    @Operation(summary = "Returns the Submodel", description = "", tags={ "Submodel Interface" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Requested Submodel", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Submodel.class))) })
    @RequestMapping(value = "/{assetIdentifier}/aas/{submodelIdentifier}/submodel",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<Submodel> getSubmodel(@PathVariable(name = "idsOffer",value="", required = false) String idsOffer, @Parameter(in = ParameterIn.PATH, description = "The Asset Administration Shells’s unique id (BASE64-URL-encoded)", required=true, schema=@Schema()) @PathVariable("assetIdentifier") String assetIdentifier, @Parameter(in = ParameterIn.PATH, description = "The Submodel’s unique id (BASE64-URL-encoded)", required=true, schema=@Schema()) @PathVariable("submodelIdentifier") String submodelIdentifier, @Parameter(in = ParameterIn.QUERY, description = "Determines the structural depth of the respective resource content" ,schema=@Schema(allowableValues={ "deep", "core" }
, defaultValue="deep")) @Valid @RequestParam(value = "level", required = false, defaultValue="deep") String level, @Parameter(in = ParameterIn.QUERY, description = "Determines the request or response kind of the resource" ,schema=@Schema(allowableValues={ "normal", "trimmed", "value", "reference", "path" }
, defaultValue="normal")) @Valid @RequestParam(value = "content", required = false, defaultValue="normal") String content, @Parameter(in = ParameterIn.QUERY, description = "Determines to which extent the resource is being serialized" ,schema=@Schema(allowableValues={ "withBlobValue", "withoutBlobValue" }
)) @Valid @RequestParam(value = "extent", required = false) String extent) {
        return getDelegate().getSubmodel(idsOffer,assetIdentifier, submodelIdentifier, level, content, extent);
    }


    @Operation(summary = "Returns a specific Submodel", description = "", tags={ "Submodel Repository Interface" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Requested Submodel", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Submodel.class))) })
    @RequestMapping(value = "/{assetIdentifier}/aas/submodels/{submodelIdentifier}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<Submodel> getSubmodelById(@PathVariable(name = "idsOffer",value="", required = false) String idsOffer, @Parameter(in = ParameterIn.PATH, description = "The Asset Administration Shells’s unique id (BASE64-URL-encoded)", required=true, schema=@Schema()) @PathVariable("assetIdentifier") String assetIdentifier, @Parameter(in = ParameterIn.PATH, description = "The Submodel’s unique id (BASE64-URL-encoded)", required=true, schema=@Schema()) @PathVariable("submodelIdentifier") String submodelIdentifier) {
        return getDelegate().getSubmodelById(idsOffer,assetIdentifier, submodelIdentifier);
    }

    @Operation(summary = "Synchronously or asynchronously invokes an Operation at a specified path", description = "", tags={ "Submodel Interface" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Operation result object", content = @Content(mediaType = "application/json", schema = @Schema(implementation = OperationResult.class))) })
    @RequestMapping(value = "/{assetIdentifier}/aas/{submodelIdentifier}/submodel/submodel-elements/{idShortPath}/invoke",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<OperationResult> invokeOperation(@PathVariable(name = "idsOffer",value="", required = false) String idsOffer, @Parameter(in = ParameterIn.PATH, description = "The Asset Administration Shells’s unique id (BASE64-URL-encoded)", required=true, schema=@Schema()) @PathVariable("assetIdentifier") String assetIdentifier, @Parameter(in = ParameterIn.PATH, description = "The Submodel’s unique id (BASE64-URL-encoded)", required=true, schema=@Schema()) @PathVariable("submodelIdentifier") String submodelIdentifier, @Parameter(in = ParameterIn.PATH, description = "IdShort path to the submodel element (dot-separated), in this case an operation", required=true, schema=@Schema()) @PathVariable("idShortPath") String idShortPath, @Parameter(in = ParameterIn.DEFAULT, description = "Operation request object", required=true, schema=@Schema()) @Valid @RequestBody OperationRequest body, @Parameter(in = ParameterIn.QUERY, description = "Determines whether an operation invocation is performed asynchronously or synchronously" ,schema=@Schema( defaultValue="false")) @Valid @RequestParam(value = "async", required = false, defaultValue="false") Boolean async, @Parameter(in = ParameterIn.QUERY, description = "Determines the request or response kind of the resource" ,schema=@Schema(allowableValues={ "normal", "trimmed", "value", "reference", "path" }
, defaultValue="normal")) @Valid @RequestParam(value = "content", required = false, defaultValue="normal") String content) {
        return getDelegate().invokeOperation(idsOffer,assetIdentifier, submodelIdentifier, idShortPath, body, async, content);
    }


}

